(function(a){function b(){var b="";for(i=0;5>i;i++)b+=Math.ceil(15*Math.random()).toString(16);return b}function c(b,a,m,e,d){b[a]?m.apply(e):(d=d||0,1E3>d&&setTimeout(function(){c(b,a,m,e,d+1)},0))}function f(b){setTimeout(function(){var m=document.createElement("script");m.type="text/javascript";m.src=b||a.fastXDM.helperUrl;c(document,"body",function(){document.getElementsByTagName("HEAD")[0].appendChild(m)})},0)}function g(b,a){n.loaded?b.apply(a,[n]):e.push([a,b])}function j(){n.loaded=!0;for(var b=
e.length;b--;)e[b][1].apply(e[b][0],[n])}function l(b,a){g(function(m){var d=m.json.parse(b);if(d[0]){d[1]||(d[1]=[]);for(m=d[1].length;m--;)if(d[1][m]._func){var e=d[1][m]._func;d[1][m]=function(){var b=Array.prototype.slice.call(arguments);b.unshift("_func"+e);a.callMethod.apply(a,b)}}setTimeout(function(){if(!a.methods[d[0]])throw Error("fastXDM: Method "+d[0]+" is undefined");a.methods[d[0]].apply(a,d[1])},0)}})}function m(b,a){for(var d in a)b[d]&&"object"==typeof b[d]?m(b[d],a[d]):b[d]=a[d]}
if(!a.fastXDM){var d={},e=[],n={};a.fastXDM={_id:0,helperUrl:"http://userapi.com/js/api/xdmHelper.js?2",Server:function(m,e){this.methods=m||{};this.id=a.fastXDM._id++;this.filter=e;this.key=b();this.methods["%init%"]=this.methods.__fxdm_i=function(){a.fastXDM.run(this.id);if(this.methods.onInit)this.methods.onInit()};this.frameName="fXD"+this.key;this.server=!0;d[this.key]=[l,this]},Client:function(b){this.methods=b||{};this.id=a.fastXDM._id++;a.fastXDM.run(this.id);if(0==window.name.indexOf("fXD"))this.key=
window.name.substr(3);else throw Error("Wrong window.name property.");this.caller=window.parent;d[this.key]=[l,this];this.client=!0;a.fastXDM.on("helper",function(){a.fastXDM.onClientStart(this)},this);g(function(b){b.send(this,b.json.stringify(["%init%"]));var a=this.methods;setTimeout(function(){if(a.onInit)a.onInit()},0)},this)},onMessage:function(b){if(!b.data)return!1;var a=b.data.substr(0,5);if(d[a]){var m=d[a][1];if(m&&(!m.filter||m.filter(b.origin)))d[a][0](b.data.substr(6),m)}},setJSON:function(b){n.json=
b},getJSON:function(b){if(!b)return n.json;g(function(a){b(a.json)})},setEnv:function(b){for(i in b)n[i]=b[i];j()},_q:{},on:function(b,a,d){this._q[b]||(this._q[b]=[]);-1==this._q[b]?a.apply(d):this._q[b].push([a,d])},run:function(b){var a=(this._q[b]||[]).length;if(this._q[b]&&0<a)for(var d=0;d<a;d++)this._q[b][d][0].apply(this._q[b][d][1]);this._q[b]=-1},waitFor:c};a.fastXDM.Server.prototype.start=function(b,d){if(b.contentWindow)this.caller=b.contentWindow,this.frame=b,a.fastXDM.on("helper",function(){a.fastXDM.onServerStart(this)},
this);else{var m=this,d=d||0;50>d&&setTimeout(function(){m.start.apply(m,[b,d+1])},100)}};a.fastXDM.Server.prototype.append=function(b,a){var d=document.createElement("DIV");d.innerHTML='<iframe name="'+this.frameName+'" ></iframe>';var e=d.firstChild,c=this;setTimeout(function(){e.frameBorder="0";a&&m(e,a);b.insertBefore(e,b.firstChild);c.start(e)},0);return e};a.fastXDM.Client.prototype.callMethod=a.fastXDM.Server.prototype.callMethod=function(){for(var b=Array.prototype.slice.call(arguments),d=
b.shift(),m=b.length;m--;)if("function"==typeof b[m]){this.funcsCount=(this.funcsCount||0)+1;var e=b[m],n="_func"+this.funcsCount;this.methods[n]=function(){e.apply(this,arguments);delete this.methods[n]};b[m]={_func:this.funcsCount}}c(this,"caller",function(){a.fastXDM.on(this.id,function(){g(function(a){a.send(this,a.json.stringify([d,b]))},this)},this)},this)};a.JSON&&"object"==typeof a.JSON&&a.JSON.parse&&a.JSON.stringify&&'{"a":[1,2,3]}'==a.JSON.stringify({a:[1,2,3]}).replace(/ /g,"")?n.json=
{parse:a.JSON.parse,stringify:a.JSON.stringify}:a.fastXDM._needJSON=!0;a.postMessage?(n.protocol="p",n.send=function(b,a){b.caller.postMessage(b.key+":"+a,"*")},a.addEventListener?a.addEventListener("message",a.fastXDM.onMessage,!1):a.attachEvent("onmessage",a.fastXDM.onMessage),a.fastXDM._needJSON?(a.fastXDM._onlyJSON=!0,f()):j()):f()}})(window);if(!window.VK)window.VK={};
if(!VK.MD5)VK.MD5=function(a){var b=function(b,a){var e=(b&65535)+(a&65535);return(b>>16)+(a>>16)+(e>>16)<<16|e&65535},c=function(b,a){return b<<a|b>>>32-a},f=function(a,d,e,n,f,h,g){return b(c(b(b(a,d&e|~d&n),b(f,g)),h),d)},g=function(a,d,e,n,f,h,g){return b(c(b(b(a,d&n|e&~n),b(f,g)),h),d)},j=function(a,d,e,f,g,h,j){return b(c(b(b(a,d^e^f),b(g,j)),h),d)},l=function(a,d,e,f,g,h,j){return b(c(b(b(a,e^(d|~f)),b(g,j)),h),d)};return function(b){for(var a="",e,f=0,c=b.length;f<c;f++)e=b.charCodeAt(f),
a+="0123456789abcdef".charAt(e>>>4&15)+"0123456789abcdef".charAt(e&15);return a}(function(a){var d=Array(a.length>>2),e,c;for(e=0,c=d.length;e<c;e++)d[e]=0;for(e=0,c=8*a.length;e<c;e+=8)d[e>>5]|=(a.charCodeAt(e/8)&255)<<e%32;var o=8*a.length,a=1732584193;e=-271733879;c=-1732584194;var h=271733878,r,q,p;d[o>>5]|=128<<o%32;d[(o+64>>>9<<4)+14]=o;for(var k=0,s=d.length;k<s;k+=16)o=a,r=e,q=c,p=h,a=f(a,e,c,h,d[k+0],7,-680876936),h=f(h,a,e,c,d[k+1],12,-389564586),c=f(c,h,a,e,d[k+2],17,606105819),e=f(e,c,
h,a,d[k+3],22,-1044525330),a=f(a,e,c,h,d[k+4],7,-176418897),h=f(h,a,e,c,d[k+5],12,1200080426),c=f(c,h,a,e,d[k+6],17,-1473231341),e=f(e,c,h,a,d[k+7],22,-45705983),a=f(a,e,c,h,d[k+8],7,1770035416),h=f(h,a,e,c,d[k+9],12,-1958414417),c=f(c,h,a,e,d[k+10],17,-42063),e=f(e,c,h,a,d[k+11],22,-1990404162),a=f(a,e,c,h,d[k+12],7,1804603682),h=f(h,a,e,c,d[k+13],12,-40341101),c=f(c,h,a,e,d[k+14],17,-1502002290),e=f(e,c,h,a,d[k+15],22,1236535329),a=g(a,e,c,h,d[k+1],5,-165796510),h=g(h,a,e,c,d[k+6],9,-1069501632),
c=g(c,h,a,e,d[k+11],14,643717713),e=g(e,c,h,a,d[k+0],20,-373897302),a=g(a,e,c,h,d[k+5],5,-701558691),h=g(h,a,e,c,d[k+10],9,38016083),c=g(c,h,a,e,d[k+15],14,-660478335),e=g(e,c,h,a,d[k+4],20,-405537848),a=g(a,e,c,h,d[k+9],5,568446438),h=g(h,a,e,c,d[k+14],9,-1019803690),c=g(c,h,a,e,d[k+3],14,-187363961),e=g(e,c,h,a,d[k+8],20,1163531501),a=g(a,e,c,h,d[k+13],5,-1444681467),h=g(h,a,e,c,d[k+2],9,-51403784),c=g(c,h,a,e,d[k+7],14,1735328473),e=g(e,c,h,a,d[k+12],20,-1926607734),a=j(a,e,c,h,d[k+5],4,-378558),
h=j(h,a,e,c,d[k+8],11,-2022574463),c=j(c,h,a,e,d[k+11],16,1839030562),e=j(e,c,h,a,d[k+14],23,-35309556),a=j(a,e,c,h,d[k+1],4,-1530992060),h=j(h,a,e,c,d[k+4],11,1272893353),c=j(c,h,a,e,d[k+7],16,-155497632),e=j(e,c,h,a,d[k+10],23,-1094730640),a=j(a,e,c,h,d[k+13],4,681279174),h=j(h,a,e,c,d[k+0],11,-358537222),c=j(c,h,a,e,d[k+3],16,-722521979),e=j(e,c,h,a,d[k+6],23,76029189),a=j(a,e,c,h,d[k+9],4,-640364487),h=j(h,a,e,c,d[k+12],11,-421815835),c=j(c,h,a,e,d[k+15],16,530742520),e=j(e,c,h,a,d[k+2],23,-995338651),
a=l(a,e,c,h,d[k+0],6,-198630844),h=l(h,a,e,c,d[k+7],10,1126891415),c=l(c,h,a,e,d[k+14],15,-1416354905),e=l(e,c,h,a,d[k+5],21,-57434055),a=l(a,e,c,h,d[k+12],6,1700485571),h=l(h,a,e,c,d[k+3],10,-1894986606),c=l(c,h,a,e,d[k+10],15,-1051523),e=l(e,c,h,a,d[k+1],21,-2054922799),a=l(a,e,c,h,d[k+8],6,1873313359),h=l(h,a,e,c,d[k+15],10,-30611744),c=l(c,h,a,e,d[k+6],15,-1560198380),e=l(e,c,h,a,d[k+13],21,1309151649),a=l(a,e,c,h,d[k+4],6,-145523070),h=l(h,a,e,c,d[k+11],10,-1120210379),c=l(c,h,a,e,d[k+2],15,
718787259),e=l(e,c,h,a,d[k+9],21,-343485551),a=b(a,o),e=b(e,r),c=b(c,q),h=b(h,p);d=[a,e,c,h];a="";e=0;for(c=32*d.length;e<c;e+=8)a+=String.fromCharCode(d[e>>5]>>>e%32&255);return a}(function(a){for(var b="",c=-1,f=a.length,g,h;++c<f;)g=a.charCodeAt(c),h=c+1<f?a.charCodeAt(c+1):0,55296<=g&&56319>=g&&56320<=h&&57343>=h&&(g=65536+((g&1023)<<10)+(h&1023),c++),127>=g?b+=String.fromCharCode(g):2047>=g?b+=String.fromCharCode(192|g>>>6&31,128|g&63):65535>=g?b+=String.fromCharCode(224|g>>>12&15,128|g>>>6&
63,128|g&63):2097151>=g&&(b+=String.fromCharCode(240|g>>>18&7,128|g>>>12&63,128|g>>>6&63,128|g&63));return b}(a)))};VK.extend=function(a,b,c){for(var f in b)if(c||"undefined"===typeof a[f])a[f]=b[f];return a};
if(VK.xdConnectionCallbacks)setTimeout(function(){for(var a;a=VK.xdConnectionCallbacks.pop();)a()},0),VK.Widgets=!1;else{VK.extend(VK,{_apiId:null,_session:null,_userStatus:"unknown",_domain:{main:"http://oauth.vkontakte.ru/",api:"https://api.vkontakte.ru/"},_path:{login:"authorize",proxy:"fxdm_oauth_proxy.html"},_rootId:"vk_api_transport",_nameTransportPath:"",xdReady:!1,access:{FRIENDS:2,PHOTOS:4,AUDIO:8,VIDEO:16,MATCHES:32,QUESTIONS:64,WIKI:128}},!0);VK.init=function(a){var b;if(!a.apiId)throw"VK.init() called without an apiId";
VK._apiId=a.apiId;if(a.vk)VK._domain.main="http://oauth.vk.com/";if(a.onlyWidgets)return!0;if(a.nameTransportPath&&""!=a.nameTransportPath)VK._nameTransportPath=a.nameTransportPath;b=document.getElementById(VK._rootId);if(!b)b=document.createElement("div"),b.id=VK._rootId,a=document.getElementsByTagName("body")[0],a.insertBefore(b,a.childNodes[0]);b.style.position="absolute";b.style.top="-10000px";if(a=VK.Cookie.load())VK.Auth._loadState="loaded",VK.Auth.setSession(a,a?"connected":"unknown")};if(!VK.Cookie)VK.Cookie=
{_domain:null,load:function(){var a=document.cookie.match("\\bvk_app_"+VK._apiId+"=([^;]*)\\b"),b;if(a){b=this.decode(a[1]);if("oauth"!=b.secret)return!1;b.expire=parseInt(b.expire,10);VK.Cookie._domain="."+window.location.hostname}return b},setRaw:function(a,b,c){var f;f="vk_app_"+VK._apiId+"="+a+"";f+=a&&0==b?"":"; expires="+(new Date(1E3*b)).toGMTString();document.cookie=f+"; path=/"+(c?"; domain=."+c:"");this._domain=c},set:function(a){a?this.setRaw(this.encode(a),a.expire,window.location.hostname):
this.clear()},clear:function(){this.setRaw("",0,this._domain)},encode:function(a){var b=[],c;for(c in a)"user"!=c&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));b.sort();return b.join("&")},decode:function(a){var b={},a=a.split("&"),c,f;for(c=0;c<a.length;c++)(f=a[c].split("=",2))&&f[0]&&(b[decodeURIComponent(f[0])]=decodeURIComponent(f[1]));return b}};if(!VK.Api)VK.Api={_headId:null,_callbacks:{},ie6_7:function(){if(!VK.Api.ieTested)VK.Api.isIE6_7=navigator.userAgent.match(/MSIE [6|7]/i),
VK.Api.ieTested=!0;return VK.Api.isIE6_7},attachScript:function(a){if(!VK.Api._headId)VK.Api._headId=document.getElementsByTagName("head")[0];var b=document.createElement("script");b.type="text/javascript";b.setAttribute("encoding","UTF-8");b.src=a;VK.Api._headId.appendChild(b)},checkMethod:function(a,b,c,f){var g=a.toLowerCase();if("wall.post"==g||"activity.set"==g){var j="activity.set"==g?b.text:b.message,j="http://vkontakte.ru/apps.php?act=a_prepare_post&widget=1&aid="+parseInt(VK._apiId)+"&text="+
encodeURIComponent(j);"wall.post"==g&&(j+="&owner_id="+parseInt(b.owner_id||0)+"&attachment="+(b.attachment||""));VK.Util.Box(j,[460,220],{proxy:function(g,j){j?c({error:j}):(b.method_access=g,VK.Api.call(a,b,c,f))}}).show();return!1}return!0},call:function(a,b,c,f){var g=b||{},j,l;if("object"!=typeof g||"function"!=typeof c)return!1;if(b.method_access||b.method_force||VK.Api.checkMethod(a,b,c,f))if(f||(f=0),"loaded"!=VK.Auth._loadState){var m=function(d){d&&d.session&&(VK.Observer.unsubscribe("auth.loginStatus",
m),VK.Api.call(a,b,c))};VK.Observer.subscribe("auth.loginStatus",m);VK.Auth.getLoginStatus()}else{if(1500>VK.Api.queryLength(g)&&!VK.Api.ie6_7()){for(var d=!1,e=parseInt(1E7*Math.random());VK.Api._callbacks[e];)e=parseInt(1E7*Math.random());g.callback="VK.Api._callbacks["+e+"]"}else d=!0;if(VK._session.sid)g.access_token=VK._session.sid;j=VK.Cookie.encode(g);l=function(g){if(g.error&&(3==g.error.error_code||4==g.error.error_code||5==g.error.error_code)){if(3<f)return!1;var j=function(d){VK.Observer.unsubscribe("auth.sessionChange",
j);delete b.access_token;d.session&&VK.Api.call(a,b,c,f+1)};VK.Observer.subscribe("auth.sessionChange",j);VK.Auth.getLoginStatus()}else c(g);d||delete VK.Api._callbacks[e]};d?VK.xdReady?VK.XDM.remote.callMethod("apiCall",a,j,l):(VK.Observer.subscribe("xdm.init",function(){VK.XDM.remote.callMethod("apiCall",a,j,l)}),VK.XDM.init()):(VK.Api._callbacks[e]=l,VK.Api.attachScript(VK._domain.api+"method/"+a+"?"+j))}},queryLength:function(a){var b=100;for(i in a)b+=i.length+encodeURIComponent(a.i).length+
1;return b}},VK.api=function(a,b,c){VK.Api.call(a,b,c)};if(!VK.Auth)VK.Auth={popup:null,lsCb:{},setSession:function(a,b,c){var f=!VK._session&&a,g=VK._session&&!a,j=VK._session&&a&&VK._session.mid!=a.mid,l=f||g||VK._session&&a&&VK._session.sid!=a.sid,m=b!=VK._userStatus,d={session:a,status:b,settings:c};VK._session=a;VK._userStatus=b;VK.Cookie.set(a);(l||m||j)&&setTimeout(function(){m&&VK.Observer.publish("auth.statusChange",d);(g||j)&&VK.Observer.publish("auth.logout",d);if(f||j)VK.xdReady&&VK.XDM.remote.init(VK._apiId,
a,b),VK.Observer.publish("auth.login",d);l&&VK.Observer.publish("auth.sessionChange",d)},0);return d},login:function(a,b){var c;if(!VK._apiId)return!1;c=VK._domain.main+VK._path.login+"?client_id="+VK._apiId+"&display=popup&redirect_uri=close.html&response_type=token";b&&0<parseInt(b)&&(c+="&scope="+b);VK.Observer.unsubscribe("auth.onLogin");VK.Observer.subscribe("auth.onLogin",a);VK.UI.popup({width:620,height:370,url:c});var f=function(){VK.Auth.getLoginStatus(function(b){VK.Observer.publish("auth.onLogin",
b);VK.Observer.unsubscribe("auth.onLogin")},!0)};VK.UI.popupOpened=!0;var g=function(){if(!VK.UI.popupOpened)return!1;try{if(!VK.UI.active.top)return VK.UI.popupOpened=!1,f(),!0}catch(b){return VK.UI.popupOpened=!1,f(),!0}setTimeout(g,100)};setTimeout(g,100)},logout:function(a){VK.Auth.revokeGrants(a)},revokeGrants:function(a){var b=function(c){VK.Observer.unsubscribe("auth.statusChange",b);a&&a(c)};VK.Observer.subscribe("auth.statusChange",b);VK._session&&VK._session.sid&&VK.Api.attachScript("https://login.vk.com/?act=openapi&oauth=1&aid="+
parseInt(VK._apiId)+"&location="+encodeURIComponent(window.location.hostname)+"&do_logout=1&token="+VK._session.sid);VK.Cookie.clear()},getSession:function(){return VK._session},getLoginStatus:function(a,b){if(VK._apiId){if(a){if(!b&&"loaded"==VK.Auth._loadState){a({status:VK._userStatus,session:VK._session});return}VK.Observer.subscribe("auth.loginStatus",a)}if(b||"loading"!=VK.Auth._loadState){VK.Auth._loadState="loading";for(var c=parseInt(1E7*Math.random());VK.Auth.lsCb[c];)c=parseInt(1E7*Math.random());
VK.Auth.lsCb[c]=function(a){delete VK.Auth.lsCb[c];VK.Auth._loadState="loaded";if(a&&a.auth){var g={mid:a.user.id,sid:a.access_token,sig:a.sig,secret:a.secret,expire:a.expire};if(b)g.user=a.user;a="connected"}else g=null,a="unknown",VK.Cookie.clear();VK.Auth.setSession(g,a);VK.Observer.publish("auth.loginStatus",{session:g,status:a});VK.Observer.unsubscribe("auth.loginStatus")};VK.Api.attachScript("https://login.vk.com/?act=openapi&oauth=1&aid="+parseInt(VK._apiId)+"&location="+encodeURIComponent(window.location.hostname)+
"&rnd="+c)}}}}}
if(!VK.UI)VK.UI={active:null,_buttons:[],popup:function(a){var b="undefined"!=typeof window.screenY?window.screenY:window.screenTop,c="undefined"!=typeof window.outerHeight?window.outerHeight:document.body.clientHeight-22,f=a.width,g=a.height,j=parseInt(("undefined"!=typeof window.screenX?window.screenX:window.screenLeft)+(("undefined"!=typeof window.outerWidth?window.outerWidth:document.body.clientWidth)-f)/2,10),b=parseInt(b+(c-g)/2.5,10);this.active=window.open(a.url,"vk_openapi","width="+f+",height="+
g+",left="+j+",top="+b)},button:function(a){var b="";"string"==typeof a&&(a=document.getElementById(a));this._buttons.push(a);index=this._buttons.length-1;a.innerHTML='<table cellspacing="0" cellpadding="0" id="openapi_UI_'+index+'" onmouseover="VK.UI._change(1, '+index+');" onmouseout="VK.UI._change(0, '+index+');" onmousedown="VK.UI._change(2, '+index+');" onmouseup="VK.UI._change(1, '+index+');" style="cursor: pointer; border: 0px; font-family: tahoma, arial, verdana, sans-serif, Lucida Sans; font-size: 10px;"><tr style="vertical-align: middle"><td><div style="border: 1px solid #3b6798;border-radius: 2px 0px 0px 2px;-moz-border-radius: 2px 0px 0px 2px;-webkit-border-radius: 2px 0px 0px 2px;"><div style="border: 1px solid #5c82ab; border-top-color: #7e9cbc; background-color: #6D8DB1; color: #fff; text-shadow: 0px 1px #45688E; height: 15px; padding: 2px 4px 0px 6px;line-height: 13px;">&#1042;&#1086;&#1081;&#1090;&#1080;</div></div></td><td><div style="background: url(http://vk.com/images/btns.png) 0px -42px no-repeat; width: 21px; height: 21px"></div></td><td><div style="border: 1px solid #3b6798;border-radius: 0px 2px 2px 0px;-moz-border-radius: 0px 2px 2px 0px;-webkit-border-radius: 0px 2px 2px 0px;"><div style="border: 1px solid #5c82ab; border-top-color: #7e9cbc; background-color: #6D8DB1; color: #fff; text-shadow: 0px 1px #45688E; height: 15px; padding: 2px 6px 0px 4px;line-height: 13px;">&#1050;&#1086;&#1085;&#1090;&#1072;&#1082;&#1090;&#1077;</div></div></td></tr></table>';
a.style.width=a.childNodes[0].offsetWidth+"px"},_change:function(a,b){for(var c=document.getElementById("openapi_UI_"+b).rows[0],f=[c.cells[0].firstChild.firstChild,c.cells[2].firstChild.firstChild],g=0;2>g;++g){var j=f[g];if(0==a)j.style.backgroundColor="#6D8DB1",j.style.borderTopColor="#7E9CBC",j.style.borderLeftColor=j.style.borderRightColor=j.style.borderBottomColor="#5C82AB";else if(1==a)j.style.backgroundColor="#7693B6",j.style.borderTopColor="#88A4C4",j.style.borderLeftColor=j.style.borderRightColor=
j.style.borderBottomColor="#6088B4";else if(2==a)j.style.backgroundColor="#6688AD",j.style.borderBottomColor="#7495B8",j.style.borderLeftColor=j.style.borderRightColor=j.style.borderTopColor="#51779F"}if(0==a||2==a)c.cells[2].firstChild.style.backgroundPosition="0px -42px";else if(1==a)c.cells[2].firstChild.style.backgroundPosition="0px -63px"}};
if(!VK.XDM)VK.XDM={remote:null,init:function(){if(this.remote)return!1;var a=VK._domain.api+VK._path.proxy;this.remote=new fastXDM.Server({onInit:function(){VK.XDM.remote.callMethod("init",VK._apiId,VK._session,VK._userStatus);VK.xdReady=!0;VK.Observer.publish("xdm.init")},setSession:{isVoid:!0,method:function(a,c){VK.Auth.setSession(a,c)}},alert:{isVoid:!0,method:function(a){alert(a)}}});this.remote.append(document.getElementById(VK._rootId),{src:a})},xdHandler:function(a){try{eval("VK."+a)}catch(b){}}};
if(!VK.Observer)VK.Observer={_subscribers:function(){if(!this._subscribersMap)this._subscribersMap={};return this._subscribersMap},publish:function(a){var b=Array.prototype.slice.call(arguments),a=b.shift(),c=this._subscribers()[a],f,g;if(c)for(f=0,g=c.length;f<g;f++)null!=c[f]&&c[f].apply(this,b)},subscribe:function(a,b){var c=this._subscribers();if("function"!=typeof b)return!1;c[a]?c[a].push(b):c[a]=[b]},unsubscribe:function(a,b){var c=this._subscribers()[a],f,g;if(!c)return!1;if("function"==typeof b)for(f=
0,g=c.length;f<g;f++)c[f]==b&&(c[f]=null);else delete this._subscribers()[a]}};
if(!VK.Widgets)VK.Widgets={},VK.Widgets.count=0,VK.Widgets.RPC={},VK.Widgets.publish=function(){VK.Observer.publish.apply(VK.Observer,arguments)},VK.Widgets.loading=function(a,b){a.style.background=b?'url("http://vk.com/images/upload.gif") center center no-repeat transparent':"none"},VK.Widgets.Comments=function(a,b,c){var f=VK.Util.getPageData();if(!VK._apiId)throw Error("VK not initialized. Please use VK.init");var b=b||{},g=function(){l.callMethod("mouseUp");return!1},j=function(a){l.callMethod("mouseMove",
{screenY:a.screenY})},l;VK.Widgets._constructor("widget_comments.php",a,b,{limit:b.limit||10,page:c||0,status_publish:void 0===b.autoPublish?1:b.autoPublish,attach:void 0===b.attach?"*":b.attach?b.attach:"",height:b.height||0,norealtime:b.norealtime?1:0,url:b.pageUrl||f.url,title:b.pageTitle||f.title,description:b.pageDescription||f.description,image:b.pageImage||f.image},{showBox:function(a,c){VK.Util.Box((b.base_domain||"http://vkontakte.ru/")+a,[c.width,c.height],{proxy:function(){l.callMethod.apply(l,
arguments)}}).show()},startDrag:function(){cursorBack=window.document.body.style.cursor;window.document.body.style.cursor="pointer";VK.Util.addEvent("mousemove",j);VK.Util.addEvent("mouseup",g)},stopDrag:function(){window.document.body.style.cursor=cursorBack;VK.Util.removeEvent("mousemove",j);VK.Util.removeEvent("mouseup",g)}},{startHeight:"133px",minWidth:300,width:"100%"},function(a,b,c){l=c});b.onChange&&(VK.Observer.subscribe("widgets.comments.new_comment",b.onChange),VK.Observer.subscribe("widgets.comments.delete_comment",
b.onChange))},VK.Widgets.Recommended=function(a,b){VK.Util.getPageData();if(!VK._apiId)throw Error("VK not initialized. Please use VK.init");var b=b||{},c={limit:b.limit||5,max:b.max||0,sort:b.sort||"friend_likes",verb:b.verb||0,period:b.period||"week",target:b.target||"parent"};VK.Widgets._constructor("widget_recommended.php",a,b,c,{},{startHeight:90+30*c.limit+"px",minWidth:150,width:"100%"})},VK.Widgets.Like=function(a,b,c){function f(a){if((o||a)&&k&&p&&k&&!("none"!=p.style.display&&"hidden"!=
p.style.visibility)){var a=b.getScrollTop?b.getScrollTop():document.body.scrollTop||document.documentElement.scrollTop||0,c=VK.Util.getXY(h,b.fixed),d=n?0:c[1];a>c[1]-120&&"top"!=b.tooltipPos||"vertical"==l||"bottom"==b.tooltipPos?(p.style.top=d+e+2+"px",k.callMethod("show",!1)):(p.style.top=d-125+"px",k.callMethod("show",!0));VK.Util.ss(p,{left:(n?0:c[0])-("vertical"==l||"mini"==l?36:2)+"px",display:"block",visibility:"visible"});o=!0}}function g(a){if((!o||a)&&k)k.callMethod("hide"),q.callMethod("hide"),
setTimeout(function(){p.style.display="none"},400)}var j=VK.Util.getPageData();if(!VK._apiId)throw Error("VK not initialized. Please use VK.init");b=VK.extend(b||{},{allowTransparency:!0});("button"==b.type||"vertical"==b.type||"mini"==b.type)&&delete b.width;var l="full"==b.type||"button"==b.type||"vertical"==b.type||"mini"==b.type?b.type:"full",m="full"==l?Math.max(200,b.width||350):"button"==l?180:"mini"==l?100:41,d=parseInt(b.height)||22,e="vertical"==l?2*d+7:"full"==l?d+1:d,c={page:c||0,url:b.pageUrl||
j.url,type:l,verb:1==b.verb?1:0,title:b.pageTitle||j.title,description:b.pageDescription||j.description,image:b.pageImage||j.image,text:(b.text||"").substr(0,140),h:d},n=b.ttHere||!1,o=!1,h,r,q,p,k,s,t;VK.Widgets._constructor("widget_like.php",a,b,c,{initTooltip:function(a){k=new fastXDM.Server({onInit:a?function(){f(!0)}:function(){},proxy:function(){q.callMethod.apply(q,arguments)},showBox:function(a,c){VK.Util.Box((b.base_domain||"http://vkontakte.ru/")+a,[c.width,c.height],{proxy:function(){k.callMethod.apply(k,
arguments)}}).show()},statsBox:function(){g(!0);t=VK.Util.Box(r.src+"&act=a_stats_box",[498,442]);t.show()}});p=k.append(n?h:document.body,{src:r.src+"&act=a_share_tooltip",scrolling:"no",allowTransparency:!0,id:r.id+"_tt",style:{position:"absolute",padding:0,display:"block",visibility:"hidden",border:"0",width:"206px",height:"127px",zIndex:5E3,overflow:"hidden"}});h.onmouseover=p.onmouseover=function(){o=!0};h.onmouseout=p.onmouseout=function(){clearTimeout(s);o=!1;s=setTimeout(function(){g()},200)}},
showTooltip:f,hideTooltip:g,showBox:function(a,c){VK.Util.Box((b.base_domain||"http://vkontakte.ru/")+a,[c.width,c.height],{proxy:function(){q.callMethod.apply(q,arguments)}}).show()},proxy:function(){k&&k.callMethod.apply(k,arguments)}},{startHeight:e+"px",minWidth:m},function(a,b,c){q=c;VK.Util.ss(h=a,{height:e+"px",width:m+"px",position:"relative",clear:"both"});VK.Util.ss(r=b,{height:e+"px",width:m+"px",overflow:"hidden",zIndex:150})})},VK.Widgets.Poll=function(a,b,c){var f=VK.Util.getPageData();
if(!VK._apiId)throw Error("VK not initialized. Please use VK.init");if(!c)throw Error("No poll id passed");b=b||{};VK.Widgets._constructor("widget_poll.php",a,b,{poll_id:c,url:b.pageUrl||f.url||location.href,title:b.pageTitle||f.title,description:b.pageDescription||f.description},{},{startHeight:"133px",minWidth:300,width:"100%"})},VK.Widgets.PagePoll=function(a,b,c){var f=VK.Util.getPageData();if(!VK._apiId)throw Error("VK not initialized. Please use VK.init");b=b||{};VK.Widgets._constructor("al_widget_poll.php",
a,b,{page:c||0,norealtime:b.norealtime?1:0,poll_id:b.pollId||"",page:c||"",url:b.pageUrl||f.url||location.href,title:b.pageTitle||f.title,description:b.pageDescription||f.description},{},{startHeight:"133px",minWidth:300,width:"100%"})},VK.Widgets.Donate=function(a,b,c){if(!c)throw Error("No merchant_id passed");c={merchant_id:c,mode:b.mode?"1":"0",users:b.users?"1":"0",test_mode:b.test_mode?"1":"0",text:b.text?"1":"0"};if(!b.width)b.width=200;VK.Widgets._constructor("widget_donate.php",a,b,c,{},
{minWidth:200,width:"200",startHeight:80})},VK.Widgets.Community=VK.Widgets.Group=function(a,b,c){function f(){j.callMethod("mouseUp");return!1}function g(a){j.callMethod("mouseMove",{screenY:a.screenY});return!1}var c=parseInt(c),j;if(!c)throw Error("No group_id passed");b.mode=parseInt(b.mode).toString();c={gid:c,mode:b.mode?b.mode:"0"};if(!b.width)b.width=200;if(b.wall)c.wall=b.wall;if(!b.height)b.height=290;var l;VK.Widgets._constructor("widget_community.php",a,b,c,{showBox:function(a,c){VK.Util.Box((b.base_domain||
"http://vkontakte.ru/")+a,[c.width,c.height],{proxy:function(){rpc.callMethod.apply(rpc,arguments)}}).show()},startDrag:function(){l=window.document.body.style.cursor;window.document.body.style.cursor="pointer";VK.Util.addEvent("mousemove",g);VK.Util.addEvent("mouseup",f)},stopDrag:function(){window.document.body.style.cursor=l;VK.Util.removeEvent("mousemove",g);VK.Util.removeEvent("mouseup",f)},auth:function(){VK.Auth.login(null,1)}},{minWidth:120,width:"200",height:"290",startHeight:200},function(a,
b,c){j=c})},VK.Widgets.Auth=function(a,b){VK.Util.getPageData();if(!VK._apiId)throw Error("VK not initialized. Please use VK.init");if(!b.width)b.width=200;type=b.type?1:0;VK.Widgets._constructor("widget_auth.php",a,b,{},{makeAuth:function(a){if(a.session)VK.Auth._loadState="loaded",VK.Auth.setSession(a.session,"connected"),VK.Observer.publish("auth.loginStatus",{session:a.session,status:"connected"}),VK.Observer.unsubscribe("auth.loginStatus");if(b.onAuth)b.onAuth(a);else{var f=b.authUrl?b.authUrl:
window.location.href,f=-1==f.indexOf("?")?f+"?":f+"&",g=[],j;for(j in a)"session"!=j&&g.push(j+"="+decodeURIComponent(a[j]));window.location.href=f+g.join("&")}}},{startHeight:80})},VK.Widgets._constructor=function(a,b,c,f,g,j,l,m){var d=document.getElementById(b);if(d){var e,n,o,h,r,q,c=c||{},j=j||{},g=g||{};e=c.base_domain||"http://vkontakte.ru";n=++VK.Widgets.count;o="auto"==c.width?d.clientWidth||"100%":parseInt(c.width);c.height?(f.height=c.height,d.height=c.height):d.height=(j.startHeight||
200)+"px";o=o?Math.max(j.minWidth||200,Math.min(1E4,o))+"px":"100%";if(!f.url)f.url=c.pageUrl||location.href.replace(/#.*$/,"");e=e+"/"+a+"?app="+(VK._apiId||"0")+"&width="+o;VK._iframeAppWidget&&(f.iframe_app=1);for(i in f){"title"==i&&80<f[i].length&&(f[i]=f[i].substr(0,80)+"...");"description"==i&&160<f[i].length&&(f[i]=f[i].substr(0,160)+"...");if("number"==typeof f[i])h=f[i];else try{h=encodeURIComponent(f[i])}catch(p){h=""}e+="&"+i+"="+h}d.style.width=o;VK.Widgets.loading(d,!0);g.publish=VK.Widgets.publish;
g.onInit=function(){VK.Widgets.loading(d,!1);if(g.onReady)g.onReady();if(c.onReady)c.onReady()};g.resize=function(a){d.style.height=a+"px";var b=document.getElementById("vkwidget"+n);if(b)b.style.height=a+"px"};r=VK.Widgets.RPC[n]=new fastXDM.Server(g,function(a){if(!a)return!0;a=a.toLowerCase();return-1!=a.indexOf(".vkontakte.ru")||-1!=a.indexOf("/vkontakte.ru")||-1!=a.indexOf(".vk.com")||-1!=a.indexOf("/vk.com")});q=VK.Widgets.RPC[n].append(d,{src:e,width:o,height:j.startHeight||"100%",scrolling:"no",
id:"vkwidget"+n,allowTransparency:c.allowTransparency||!1,style:{overflow:"hidden"}});l&&setTimeout(function(){l(d,q||d.firstChild,r)},10);return!0}m=m||0;if(10<m)throw Error("VK.Widgets: object #"+b+" not found.");setTimeout(function(){VK.Widgets._constructor(a,b,c,f,g,j,l,m+1)},500)};
VK.Util={getPageData:function(){if(!VK._pData){var a=document.getElementsByTagName("meta"),b={},c=["description","title","url","image","app_id"],f,g;for(g in a)if(a[g].getAttribute&&a[g].getAttribute&&((f=a[g].getAttribute("name"))||(f=a[g].getAttribute("property"))))for(var j in c)if(f==c[j]||f=="og:"+c[j]||f=="vk:"+c[j])b[c[j]]=a[g].content;if(b.app_id&&!VK._apiId)VK._apiId=b.app_id;b.title=b.title||document.title||"";b.description=b.description||"";b.image=b.image||"";if(!b.url&&VK._iframeAppWidget&&
VK._apiId)b.url="/app"+VK._apiId,VK._browserHash&&(b.url+=VK._browserHash);a=location.href.replace(/#.*$/,"");if(!b.url||!b.url.indexOf(a))b.url=a;VK._pData=b}return VK._pData},getXY:function(a,b){if(a&&void 0!=a){var c=0,f=0;if(a.offsetParent){do c+=a.offsetLeft,f+=a.offsetTop,b&&(c-=a.scrollLeft,f-=a.scrollTop);while(a=a.offsetParent)}b&&(f+=window.pageYOffset||scrollNode.scrollTop||document.documentElement.scrollTop);return[c,f]}},Box:function(a,b,c){var c=c||{},f=new fastXDM.Server(VK.extend(c,
{onInit:function(){g.style.background="transparent"},hide:function(){g.style.display="none"},destroy:function(){delete f;try{g.src="about: blank;"}catch(a){}g.parentNode.removeChild(g)},resize:function(a,c){b[0]=a;b[1]=c;VK.Util.ss(g,{width:b[0]+"px",height:b[1]+"px"});j()}},!0)),g=f.append(document.body,{src:a,scrolling:"no",allowTransparency:!0,style:{position:"absolute",left:"50%",zIndex:1002,background:"http://vkontakte.ru/images/upload.gif center center no-repeat transparent",padding:"0",border:"0",
width:b[0]+"px",height:b[1]+"px",overflow:"hidden"}}),j=function(a,c){var c=Math.min(1E3,c||(window.innerHeight?window.innerHeight:document.documentElement.clientHeight?document.documentElement.clientHeight:document.body.offsetHeight)),a=a||Math.max(parseInt(window.pageYOffset)||0,document.documentElement.scrollTop,document.body.scrollTop),d=Math.max(0,a+(c-b[1])/3);VK.Util.ss(g,{top:d+"px",margin:"0 0 0 "+-b[0]/2+"px"})};return{show:function(a,b){j(a,b);g.style.display="block"},hide:function(){g.style.display=
"none"},iframe:g,rpc:f}},addEvent:function(a,b){window.document.addEventListener?window.document.addEventListener(a,b,!1):window.document.attachEvent&&window.document.attachEvent("on"+a,b)},removeEvent:function(a,b){window.document.removeEventListener?window.document.removeEventListener(a,b,!1):window.document.detachEvent&&window.document.detachEvent("on"+a,b)},ss:function(a,b){VK.extend(a.style,b,!0)}};window.vkAsyncInit&&setTimeout(vkAsyncInit,0);